os: linux
sudo: required
dist: xenial
language: python

matrix:
    include:
        - python: 3.7
          env: TOXENV=py,lowest,codecov
        - python: 3.6
          env: TOXENV=py,lowest,codecov
        - python: 3.5
          env: TOXENV=py,codecov
        - python: 3.4
          env: TOXENV=py,codecov
        - python: 2.7
          env: TOXENV=py,lowest,codecov
        - python: pypy3.5
          env: TOXENV=py,lowest,codecov

install:
    - pip install tox

script:
    - tox

cache:
    - pip

notifications:
    email: false
